/*
INSERT INTO users (email, password, surname, name, patronymic)
VALUES (
        'admin@mail.ru',
        '$2a$12$uqUEJ9BZ0Knb5FrN3cu7PO3Ko2VCjegb1t3isidrw4H1dtmW/YFgO',
        'Султанов',
        'Ильнар',
        'Наилевич'
);

INSERT INTO users (email, password, surname, name, patronymic)
VALUES (
        'user@mail.ru',
        '$2a$12$bOiiHDBFmVfOPZfqtLG0FOkQHsaK9Ly2Ezevs9RjFciRICDMdkRSa',
        'Сарычев',
        'Кирилл',
        'Игоревич'
);

INSERT INTO roles (title) VALUES ('ROLE_ADMIN'), ('ROLE_USER');

INSERT INTO user_role (user_id, role_id)
VALUES (1, 1), (2, 2);


INSERT INTO QUESTIONNAIRES (TITLE) VALUES ('О СЕБЕ')

INSERT INTO QUESTIONS (QUESTION_TEXT , NUMBER_OF_CHOICES , QUESTIONNAIRE_ID)
VALUES ('Сколько вам лет?', 'ONE', 1)

INSERT INTO ANSWER_FOR_QUESTION (ANSWER_TEXT, QUESTION_ID )
VALUES ('Меньше 25', 1), ('25-40', 1), ('Больше 40', 1)

INSERT INTO QUESTIONS (QUESTION_TEXT , NUMBER_OF_CHOICES , QUESTIONNAIRE_ID)
VALUES ('Ваше хобби?', 'MANY', 1)

INSERT INTO ANSWER_FOR_QUESTION (ANSWER_TEXT, QUESTION_ID)
VALUES ('Спорт', 2),  ('Рисование', 2), ('Пение', 2),  ('Готовка', 2),   ('Компьютерные игры', 2),
    ('Чтение', 2),  ('Вязание', 2), ('Игра на музыкальных инструментах', 2)


Hibernate:

    create table answers (
       id bigint generated by default as identity,
        answer_for_question_id bigint,
        question_id bigint,
        user_id bigint,
        primary key (id)
    )
Hibernate:

    create table questionnaires (
       id bigint generated by default as identity,
        title varchar(255) not null,
        primary key (id)
    )
Hibernate:

    create table questions (
       id bigint generated by default as identity,
        number_of_choices varchar(255) not null,
        question_text varchar(255) not null,
        questionnaire_id bigint,
        primary key (id)
    )
Hibernate:

    create table roles (
       id bigint generated by default as identity,
        title varchar(255) not null,
        primary key (id)
    )
Hibernate:

    create table user_role (
       user_id bigint not null,
        role_id bigint not null
    )
Hibernate:

    create table users (
       id bigint generated by default as identity,
        email varchar(255) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        patronymic varchar(255) not null,
        surname varchar(255) not null,
        primary key (id)
    )
Hibernate:

    alter table questionnaires
       add constraint UK_e44jkqi3gvc82c7w18335bado unique (title)
Hibernate:

    alter table roles
       add constraint UK_nodjpaox51kclukt7yi0hf6qf unique (title)
Hibernate:

    alter table users
       add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
Hibernate:

    alter table answer_for_question
       add constraint FK6f78al5aoejo1evxhys4rkrrh
       foreign key (question_id)
       references questions
Hibernate:

    alter table answers
       add constraint FK92am1r593xgpa2jkp7sjubr7v
       foreign key (answer_for_question_id)
       references answer_for_question
Hibernate:

    alter table answers
       add constraint FK3erw1a3t0r78st8ty27x6v3g1
       foreign key (question_id)
       references questions
Hibernate:

    alter table answers
       add constraint FK5bp3d5loftq2vjn683ephn75a
       foreign key (user_id)
       references users
Hibernate:

    alter table questions
       add constraint FKepjy1stu0ygdyo8h3ye7dcsqg
       foreign key (questionnaire_id)
       references questionnaires
Hibernate:

    alter table user_role
       add constraint FKt7e7djp752sqn6w22i6ocqy6q
       foreign key (role_id)
       references roles
Hibernate:

    alter table user_role
       add constraint FKj345gk1bovqvfame88rcx7yyx
       foreign key (user_id)
       references users
*/
